const countryCapitals = [
    {
        country:"Afghanistan",
        city:"Kabul"
    },
    {
        country:"Albania",
        city:"Tirana"
    },
    {
        country:"Algeria",
        city:"Alger"
    },
    {
        country:"Andorra",
        city:"Andorra la Vella"
    },
    {
        country:"Angola",
        city:"Luanda"
    },
    {
        country:"Argentina",
        city:"Buenos Aires"
    },
    {
        country:"Armenia",
        city:"Yerevan"
    },
    {
        country:"Australia",
        city:"Canberra"
    },
    {
        country:"Austria",
        city:"Wien"
    },
    {
        country:"Azerbaijan",
        city:"Baku"
    },
    {
        country:"Belarus",
        city:"Minsk"
    },
    {
        country:"Bolivia",
        city:"La Paz"
    },
    {
        country:"Bosnia and Herzegovina",
        city:"Sarajevo"
    },
    {
        country:"Botswana",
        city:"Gaborone"
    },
    {
        country:"Brazil",
        city:"Brasília"
    },
    {
        country:"Bulgaria",
        city:"Sofia"
    },
    {
        country:"Canada",
        city:"Ottawa"
    },
    {
        country:"Croatia",
        city:"Zagreb"
    },
    {
        country:"Bangladesh",
        city:"Dhaka"
    },
    {
        country:"Cuba",
        city:"La Habana"
    },
    {
        country:"Cyprus",
        city:"Nicosia"
    },
    {
        country:"Czech Republic",
        city:"Praha"
    },
    {
        country:"Denmark",
        city:"Copenhagen"
    },
    {
        country:"Egypt",
        city:"Cairo"
    },
    {
        country:"Ecuador",
        city:"Quito"
    },
    {
        country:"Djibouti",
        city:"Djibouti"
    },
    {
        country:"Estonia",
        city:"Tallinn"
    },
    {
        country:"England",
        city:"London"
    },
    {
        country:"Ethiopia",
        city:"Addis Abeba"
    },
    {
        country:"Faroe Islands",
        city:"Tórshavn"
    },
    {
        country:"Fiji Islands",
        city:"Suva"
    },
    {
        country:"Georgia",
        city:"Tbilisi"
    },
    {
        country:"France",
        city:"Paris"
    },
    {
        country:"Germany",
        city:"Berlin"
    },
    {
        country:"Ghana",
        city:"Accra"
    },
    {
        country:"Hungary",
        city:"Budapest"
    },
    {
        country:"India",
        city:"New Delhi"
    },
    {
        country:"Iran",
        city:"Tehran"
    },
    {
        country:"Indonesia",
        city:"Jakarta"
    },
    {
        country:"Ireland",
        city:"Dublin"
    },
    {
        country:"Iraq",
        city:"Baghdad"
    },
    {
        country:"Italy",
        city:"Roma"
    },
    {
        country:"Israel",
        city:"Jerusalem"
    },
    {
        country:"Ivory Coast",
        city:"Yamoussoukro"
    },
    {
        country:"Jamaica",
        city:"Kingston"
    },
    {
        country:"Kenya",
        city:"Nairobi"
    },
    {
        country:"Jordan",
        city:"Amman"
    },
    {
        country:"Japan",
        city:"Tokyo"
    },
    {
        country:"Kazakhstan",
        city:"Astana"
    },
    {
        country:"Kuwait",
        city:"Kuwait"
    },
    {
        country:"Kyrgyzstan",
        city:"Bishkek"
    },
    {
        country:"Latvia",
        city:"Riga"
    },
    {
        country:"Lithuania",
        city:"Vilnius"
    },
    {
        country:"Lebanon",
        city:"Beirut"
    },
    {
        country:"Liechtenstein",
        city:"Vaduz"
    },
    {
        country:"North Macedonia",
        city:"Skopje"
    },
    {
        country:"Malaysia",
        city:"Kuala Lumpur"
    },
    {
        country:"Madagascar",
        city:"Antananarivo"
    },
    {
        country:"Malawi",
        city:"Lilongwe"
    },
    {
        country:"Maldives",
        city:"Male"
    },
    {
        country:"Mali",
        city:"Bamako"
    },
    {
        country:"Malta",
        city:"Valletta"
    },
    {
        country:"Moldova",
        city:"Chisinau"
    },
    {
        country:"Monaco",
        city:"Monaco-Ville"
    },
    {
        country:"Mongolia",
        city:"Ulan Bator"
    },
    {
        country:"Netherlands",
        city:"Amsterdam"
    },
    {
        country:"Morocco",
        city:"Rabat"
    },
    {
        country:"Nicaragua",
        city:"Managua"
    },
    {
        country:"Montenegro",
        city:"Podgorica"
    },
    {
        country:"Nepal",
        city:"Kathmandu"
    },
    {
        country:"New Zealand",
        city:"Wellington"
    },
    {
        country:"Norway",
        city:"Oslo"
    },
    {
        country:"Nigeria",
        city:"Abuja"
    },
    {
        country:"Pakistan",
        city:"Islamabad"
    },
    {
        country:"Niger",
        city:"Niamey"
    },
    {
        country:"North Korea",
        city:"Pyongyang"
    },
    {
        country:"Palestine",
        city:"Gaza"
    },
    {
        country:"Papua New Guinea",
        city:"Port Moresby"
    },
    {
        country:"Peru",
        city:"Lima"
    },
    {
        country:"Philippines",
        city:"Manila"
    },
    {
        country:"Poland",
        city:"Warszawa"
    },
    {
        country:"Portugal",
        city:"Lisboa"
    },
    {
        country:"Puerto Rico",
        city:"San Juan"
    },
    {
        country:"Qatar",
        city:"Doha"
    },
    {
        country:"Russian Federation",
        city:"Moscow"
    },
    {
        country:"Rwanda",
        city:"Kigali"
    },
    {
        country:"San Marino",
        city:"San Marino"
    },
    {
        country:"Saudi Arabia",
        city:"Riyadh"
    },
    {
        country:"Scotland",
        city:"Edinburgh"
    },
    {
        country:"Singapore",
        city:"Singapore"
    },
    {
        country:"Slovakia",
        city:"Bratislava"
    },
    {
        country:"Serbia",
        city:"Belgrade"
    },
    {
        country:"Slovenia",
        city:"Ljubljana"
    },
    {
        country:"Senegal",
        city:"Dakar"
    },
    {
        country:"Sudan",
        city:"Khartum"
    },
    {
        country:"South Korea",
        city:"Seoul"
    },
    {
        country:"Spain",
        city:"Madrid"
    },
    {
        country:"South Africa",
        city:"Pretoria"
    },
    {
        country:"South Sudan",
        city:"Juba"
    },
    {
        country:"Sweden",
        city:"Stockholm"
    },
    {
        country:"Switzerland",
        city:"Bern"
    },
    {
        country:"Tajikistan",
        city:"Dushanbe"
    },
    {
        country:"Swaziland",
        city:"Mbabane"
    },
    {
        country:"Syria",
        city:"Damascus"
    },
    {
        country:"Tanzania",
        city:"Dodoma"
    },
    {
        country:"Thailand",
        city:"Bangkok"
    },
    {
        country:"The Democratic Republic of Congo",
        city:"Kinshasa"
    },
    {
        country:"Tunisia",
        city:"Tunis"
    },
    {
        country:"Togo",
        city:"Lom"
    },
    {
        country:"Turkey",
        city:"Ankara"
    },
    {
        country:"Uganda",
        city:"Kampala"
    },
    {
        country:"United Arab Emirates",
        city:"Abu Dhabi"
    },
    {
        country:"Ukraine",
        city:"Kyiv"
    },
    {
        country:"Turkmenistan",
        city:"Ashgabat"
    },
    {
        country:"United States",
        city:"Washington"
    },
    {
        country:"United Kingdom",
        city:"London"
    },
    {
        country:"Uruguay",
        city:"Montevideo"
    },
    {
        country:"Venezuela",
        city:"Caracas"
    },
    {
        country:"Vietnam",
        city:"Hanoi"
    },
    {
        country:"Wales",
        city:"Cardiff"
    },
    {
        country:"Wallis and Futuna",
        city:"Mata-Utu"
    },
    {
        country:"Zambia",
        city:"Lusaka"
    },
    {
        country:"Zimbabwe",
        city:"Harare"
    }
]